/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewPolicy {
  'id' : bigint,
  'policyType' : string,
  'name' : string,
  'description' : string,
}
export type Role = { 'admin' : null } |
  { 'user' : null } |
  { 'viewer' : null };
export interface SecurityPolicy {
  'id' : bigint,
  'policyType' : string,
  'name' : string,
  'digitalSignature' : [] | [string],
  'description' : string,
  'enabled' : boolean,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface Threat {
  'id' : bigint,
  'resolved' : boolean,
  'description' : string,
  'threatType' : ThreatType,
  'timestamp' : Time,
  'severity' : Severity,
}
export type ThreatType = { 'unauthorizedAccess' : null } |
  { 'ddos' : null } |
  { 'phishing' : null } |
  { 'malware' : null };
export type Time = bigint;
export interface UpdatePolicyParams {
  'policyType' : string,
  'name' : string,
  'description' : string,
  'enabled' : boolean,
}
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[bigint], undefined>,
  'addIncident' : ActorMethod<[string, Severity], bigint>,
  'addScan' : ActorMethod<[Array<string>, Severity], bigint>,
  'addSecurityPolicy' : ActorMethod<[NewPolicy], bigint>,
  'addThreat' : ActorMethod<[ThreatType, Severity, string], bigint>,
  'enablePolicy' : ActorMethod<[bigint], undefined>,
  'getAllPolicies' : ActorMethod<[], Array<SecurityPolicy>>,
  'getPolicySignature' : ActorMethod<[bigint], [] | [string]>,
  'getUnresolvedThreats' : ActorMethod<[], Array<Threat>>,
  'registerUser' : ActorMethod<[string, Role], undefined>,
  'storePolicySignature' : ActorMethod<[bigint, string], undefined>,
  'updatePolicy' : ActorMethod<[bigint, boolean], undefined>,
  'updateSecurityPolicy' : ActorMethod<[bigint, UpdatePolicyParams], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];