/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const NewPolicy = IDL.Record({
  'id' : IDL.Nat,
  'policyType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ThreatType = IDL.Variant({
  'unauthorizedAccess' : IDL.Null,
  'ddos' : IDL.Null,
  'phishing' : IDL.Null,
  'malware' : IDL.Null,
});
export const SecurityPolicy = IDL.Record({
  'id' : IDL.Nat,
  'policyType' : IDL.Text,
  'name' : IDL.Text,
  'digitalSignature' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const Time = IDL.Int;
export const Threat = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'description' : IDL.Text,
  'threatType' : ThreatType,
  'timestamp' : Time,
  'severity' : Severity,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'viewer' : IDL.Null,
});
export const UpdatePolicyParams = IDL.Record({
  'policyType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
  'addIncident' : IDL.Func([IDL.Text, Severity], [IDL.Nat], []),
  'addScan' : IDL.Func([IDL.Vec(IDL.Text), Severity], [IDL.Nat], []),
  'addSecurityPolicy' : IDL.Func([NewPolicy], [IDL.Nat], []),
  'addThreat' : IDL.Func([ThreatType, Severity, IDL.Text], [IDL.Nat], []),
  'enablePolicy' : IDL.Func([IDL.Nat], [], []),
  'getAllPolicies' : IDL.Func([], [IDL.Vec(SecurityPolicy)], ['query']),
  'getPolicySignature' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getUnresolvedThreats' : IDL.Func([], [IDL.Vec(Threat)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, Role], [], []),
  'storePolicySignature' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePolicy' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateSecurityPolicy' : IDL.Func([IDL.Nat, UpdatePolicyParams], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const NewPolicy = IDL.Record({
    'id' : IDL.Nat,
    'policyType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ThreatType = IDL.Variant({
    'unauthorizedAccess' : IDL.Null,
    'ddos' : IDL.Null,
    'phishing' : IDL.Null,
    'malware' : IDL.Null,
  });
  const SecurityPolicy = IDL.Record({
    'id' : IDL.Nat,
    'policyType' : IDL.Text,
    'name' : IDL.Text,
    'digitalSignature' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Threat = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'description' : IDL.Text,
    'threatType' : ThreatType,
    'timestamp' : Time,
    'severity' : Severity,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const UpdatePolicyParams = IDL.Record({
    'policyType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
    'addIncident' : IDL.Func([IDL.Text, Severity], [IDL.Nat], []),
    'addScan' : IDL.Func([IDL.Vec(IDL.Text), Severity], [IDL.Nat], []),
    'addSecurityPolicy' : IDL.Func([NewPolicy], [IDL.Nat], []),
    'addThreat' : IDL.Func([ThreatType, Severity, IDL.Text], [IDL.Nat], []),
    'enablePolicy' : IDL.Func([IDL.Nat], [], []),
    'getAllPolicies' : IDL.Func([], [IDL.Vec(SecurityPolicy)], ['query']),
    'getPolicySignature' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getUnresolvedThreats' : IDL.Func([], [IDL.Vec(Threat)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, Role], [], []),
    'storePolicySignature' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePolicy' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateSecurityPolicy' : IDL.Func([IDL.Nat, UpdatePolicyParams], [], []),
  });
};

export const init = ({ IDL }) => { return []; };