/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface UpdatePolicyParams {
    policyType: string;
    name: string;
    description: string;
    enabled: boolean;
}
export interface Threat {
    id: bigint;
    resolved: boolean;
    description: string;
    threatType: ThreatType;
    timestamp: Time;
    severity: Severity;
}
export interface SecurityPolicy {
    id: bigint;
    policyType: string;
    name: string;
    digitalSignature?: string;
    description: string;
    enabled: boolean;
}
export interface NewPolicy {
    id: bigint;
    policyType: string;
    name: string;
    description: string;
}
export enum Role {
    admin = "admin",
    user = "user",
    viewer = "viewer"
}
export enum Severity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum ThreatType {
    unauthorizedAccess = "unauthorizedAccess",
    ddos = "ddos",
    phishing = "phishing",
    malware = "malware"
}
export interface backendInterface {
    acknowledgeAlert(alertId: bigint): Promise<void>;
    addIncident(description: string, severity: Severity): Promise<bigint>;
    addScan(findings: Array<string>, severity: Severity): Promise<bigint>;
    addSecurityPolicy(newPolicy: NewPolicy): Promise<bigint>;
    addThreat(threatType: ThreatType, severity: Severity, description: string): Promise<bigint>;
    enablePolicy(policyId: bigint): Promise<void>;
    getAllPolicies(): Promise<Array<SecurityPolicy>>;
    getPolicySignature(policyId: bigint): Promise<string | null>;
    getUnresolvedThreats(): Promise<Array<Threat>>;
    registerUser(username: string, _role: Role): Promise<void>;
    storePolicySignature(policyId: bigint, signature: string): Promise<void>;
    updatePolicy(policyId: bigint, enabled: boolean): Promise<void>;
    updateSecurityPolicy(id: bigint, update: UpdatePolicyParams): Promise<void>;
}
import type { Role as _Role, SecurityPolicy as _SecurityPolicy, Severity as _Severity, Threat as _Threat, ThreatType as _ThreatType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async addIncident(arg0: string, arg1: Severity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncident(arg0, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncident(arg0, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addScan(arg0: Array<string>, arg1: Severity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addScan(arg0, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScan(arg0, to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addSecurityPolicy(arg0: NewPolicy): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSecurityPolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSecurityPolicy(arg0);
            return result;
        }
    }
    async addThreat(arg0: ThreatType, arg1: Severity, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addThreat(to_candid_ThreatType_n3(this._uploadFile, this._downloadFile, arg0), to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addThreat(to_candid_ThreatType_n3(this._uploadFile, this._downloadFile, arg0), to_candid_Severity_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async enablePolicy(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enablePolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enablePolicy(arg0);
            return result;
        }
    }
    async getAllPolicies(): Promise<Array<SecurityPolicy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPolicies();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPolicies();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPolicySignature(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicySignature(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicySignature(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnresolvedThreats(): Promise<Array<Threat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnresolvedThreats();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnresolvedThreats();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, to_candid_Role_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, to_candid_Role_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async storePolicySignature(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storePolicySignature(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePolicySignature(arg0, arg1);
            return result;
        }
    }
    async updatePolicy(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePolicy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePolicy(arg0, arg1);
            return result;
        }
    }
    async updateSecurityPolicy(arg0: bigint, arg1: UpdatePolicyParams): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSecurityPolicy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSecurityPolicy(arg0, arg1);
            return result;
        }
    }
}
function from_candid_SecurityPolicy_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecurityPolicy): SecurityPolicy {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatType): ThreatType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Threat_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Threat): Threat {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    resolved: boolean;
    description: string;
    threatType: _ThreatType;
    timestamp: _Time;
    severity: _Severity;
}): {
    id: bigint;
    resolved: boolean;
    description: string;
    threatType: ThreatType;
    timestamp: Time;
    severity: Severity;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        description: value.description,
        threatType: from_candid_ThreatType_n12(_uploadFile, _downloadFile, value.threatType),
        timestamp: value.timestamp,
        severity: from_candid_Severity_n14(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    policyType: string;
    name: string;
    digitalSignature: [] | [string];
    description: string;
    enabled: boolean;
}): {
    id: bigint;
    policyType: string;
    name: string;
    digitalSignature?: string;
    description: string;
    enabled: boolean;
} {
    return {
        id: value.id,
        policyType: value.policyType,
        name: value.name,
        digitalSignature: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.digitalSignature)),
        description: value.description,
        enabled: value.enabled
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unauthorizedAccess: null;
} | {
    ddos: null;
} | {
    phishing: null;
} | {
    malware: null;
}): ThreatType {
    return "unauthorizedAccess" in value ? ThreatType.unauthorizedAccess : "ddos" in value ? ThreatType.ddos : "phishing" in value ? ThreatType.phishing : "malware" in value ? ThreatType.malware : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "critical" in value ? Severity.critical : "medium" in value ? Severity.medium : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SecurityPolicy>): Array<SecurityPolicy> {
    return value.map((x)=>from_candid_SecurityPolicy_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Threat>): Array<Threat> {
    return value.map((x)=>from_candid_Threat_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ThreatType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatType): _ThreatType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} | {
    viewer: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value == Role.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.critical ? {
        critical: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThreatType): {
    unauthorizedAccess: null;
} | {
    ddos: null;
} | {
    phishing: null;
} | {
    malware: null;
} {
    return value == ThreatType.unauthorizedAccess ? {
        unauthorizedAccess: null
    } : value == ThreatType.ddos ? {
        ddos: null
    } : value == ThreatType.phishing ? {
        phishing: null
    } : value == ThreatType.malware ? {
        malware: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
